In [3]:
import pandas as pd

#load mite_data
mite_data = pd.read_csv('mite_data.csv')

mite_data

,mite ID,zone ID,status,max diff,local diff,recording,status_num,streak_start
0,mite_0001,dead,dead,11.0,9.666667,1,1.0,1.0
1,mite_0001,dead,dead,11.0,10.666667,2,1.0,1.0
2,mite_0001,dead,dead,11.0,10.333333,3,1.0,1.0
3,mite_0001,dead,dead,12.0,10.000000,4,1.0,1.0
4,mite_0001,dead,dead,10.0,10.000000,5,1.0,1.0
...,...,...,...,...,...,...,...,...
451,mite_0058,dead,dead,13.0,11.666667,4,1.0,1.0
452,mite_0058,dead,dead,14.0,12.333333,5,1.0,1.0
453,mite_0058,dead,dead,14.0,12.000000,6,1.0,1.0
454,mite_0058,dead,dead,12.0,11.666667,7,1.0,1.0
455,mite_0058,dead,dead,13.0,12.666667,8,1.0,1.0

In [7]:
# now make a summary df where for each zone you find total mites, alive mites, and dead mites,for each  recording num
summary_df = mite_data.groupby(['zone ID', 'recording']).agg(
    total_mites=('mite ID', 'count'),
    alive_mites=('status', lambda x: (x == 'alive').sum()),
    dead_mites=('status', lambda x: (x == 'dead').sum())
).reset_index()

summary_df

   zone ID  recording  total_mites  alive_mites  dead_mites
0    alive          1           23           18           5
1    alive          2           23           18           5
2    alive          3           23            7          16
3    alive          4           23            8          15
4    alive          5           23            7          16
5    alive          6           23            4          19
6    alive          7           23            3          20
7    alive          8           23            2          21
8     dead          1           34            0          34
9     dead          2           34            0          34
10    dead          3           34            0          34
11    dead          4           34            0          34
12    dead          5           34            0          34
13    dead          6           34            0          34
14    dead          7           34            0          34
15    dead          8           34            0          34